### PR TITLE
 Resolve #13: Fix type for heatmap plotting 

### LINKED ISSUE #13: Questions regarding Section 3
1. The variable `pars` in Notebook 3 (line 3, cell 102/138) is not defined. I think instead, we can directly use `testdata` inplace, or we have to change/define the variable `pars` before using it.
```julia
model = "linear"
testdata = @strdict a b c model
savename("prefix", pars, "jld2")
```

2. I think parameter for solution of "Bouncing ball" exercise should be `p₀ = [10, 0.99]` as mentioned in the instruction of Notebook 3 that use gravity constant $g=10$
https://github.com/Datseris/Zero2Hero-JuliaWorkshop/blob/3929cb090214ced54bd73f5eee0ecb806c8c667b/solutions_3.jl#L8

3. In the instruction of "Distribution quantile" exercise, I think we can write the formula (cell 133/138) as
$$\theta_{n+1} = \theta_n -\frac{\text{cdf}(\theta_n)−q}{\text{pdf}(\theta_n)}$$
instead of
$$\theta_{n+1} = \theta_n -\frac{\text{cdf}(\theta)−q}{\text{pdf}(\theta)}$$
In my case, at first glance I confused between $\theta$ and $\theta_n$ / $\theta_{n+1}$.

4. I have some errors using the solution for "DataFrame of chaos" exercise, heatmap plotting task. I get the message "StackOverflowError" when running the line
https://github.com/Datseris/Zero2Hero-JuliaWorkshop/blob/3929cb090214ced54bd73f5eee0ecb806c8c667b/solutions_3.jl#L98
When I delete 2 arguments `bs` and `cs` (the line becomes `fig, ax, hm = heatmap(heat)`), I do not get the error and get the heatmap successfully plotted. Can you re-run on your local to double check this?

5. In the solution for "DataFrame of chaos" exercise, you call directly Roessler built-in function
https://github.com/Datseris/Zero2Hero-JuliaWorkshop/blob/3929cb090214ced54bd73f5eee0ecb806c8c667b/solutions_3.jl#L60
While in my case I use
```julia
function RoesslerDynamicalSystem(u, p, t)
    x, y, z = u
    a, b, c = p
    xdot = - y - z
    ydot = x + a*y
    zdot = b + z*(x - c)
    return SVector(xdot, ydot, zdot)
end

ro = CoupledODEs(RoesslerDynamicalSystem, ones(3), [0.2, 0.2, 5.7])
```
The numbers `[0.2, 0.2, 5.7]` of parameters is what I have found at this [link of documentation](https://juliadynamics.github.io/PredefinedDynamicalSystems.jl/dev/#PredefinedDynamicalSystems.roessler). All the other things stay the same. However, I get slightly different plots

Built-in function | My own function
:-------------------------:|:-------------------------:
Scatter plot when using built-in function  |  Scatter plot when using my own function
Heatmap when using built-in function  |  Heatmap when using my own function

P/s: I do not have much knowledge in ODEs, DEs in general. So I will be very happy if you can correct me if I am wrong anywhere above. Furthermore, we currently do not have solution for "Textbook optimization problem" exercise, very happy to make a PR to contribute for that, and also fix some typos along the way.

### PR DESCRIPTION
**Pull request by nhattan417**
Resolve #13. 
Makie errors when trying to plot missing so we need to convert the type.

### CODE REVIEW

File: solutions_3.jl [hunk 1]
```diff
@@ -94,7 +94,10 @@ heatdf = @from row in df begin
 end
 
 unstacked = unstack(heatdf, :b,  :H; renamecols = (x -> "H for b=$(x)"))
-heat = Matrix(unstacked[:, Not(:c)])
+
+# Makie errors when trying to plot missing so we need to convert the type.
+disallowmissing!(unstacked)heat = Matrix(unstacked[:, Not(:c)])
```
Comment (Datseris) [inline solutions_3.jl]:
```suggestion
disallowmissing!(unstacked)
heat = Matrix(unstacked[:, Not(:c)])
```
